name: Confirm Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "1 5 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Build easyblog binary
        run: go build -o easyblog .

      - name: Build site with EasyBlog
        run: ./easyblog

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: "edf6d7f2ca065ebdfe0109ef54c7bb89"
          wranglerVersion: "4.20.0"
